# Generated by Django 4.1.7 on 2023-02-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
