# Generated by Django 4.1.7 on 2023-03-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'Created'), (1, 'Paid'), (2, 'On way'), (3, 'Delivered'), (4, 'Canceled')], default=1, max_length=20),
        ),
    ]
